#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments
#------------------------------------------------------------------------------


wmake $targetType
wmake $targetType VOFDBMcavitation2DyMFoam
wmake $targetType overVOFDBMcavitation2DyMFoam

#------------------------------------------------------------------------------
